### ISSUE TITLE
Incompatibility with Shaderpacks

### ISSUE THREAD

**Issue by SrRapero720** [SrRapero720/WATERFrAMES#1]
# TESTED SHADERS WITH ISSUES

- MakeUp Ultrafast 8.7a
  - Using realistic clouds renders nothing

- BSL
  - Using realistic clouds renders nothing
  - Breaks picture changing transparency (in frame)

- AstralAlex
  - Using static/dynamic clouds renders nothing

- projectLUMA
  - Torchlight Mappings breaks image color (become black)
  - Little breaks picture changing transparency (in frame)

### BLS SCREENSHOTS
Using Waterframes transparency option
![2023-03-13_17h37_10](https://user-images.githubusercontent.com/29090346/224857022-351c05ba-d244-4b81-a0ba-a6dcea0db64e.png)
![2023-03-13_17h37_16](https://user-images.githubusercontent.com/29090346/224857023-70167700-d2ea-4458-be0e-5259cadaf4e4.png)

Realistic clouds
![2023-03-13_15h24_47](https://user-images.githubusercontent.com/29090346/224858012-4235bf54-7cea-4394-83c6-755eed180aff.png)

***

### LUMA SCREENSHOTS
torch mapping
![2023-03-13_17h39_40](https://user-images.githubusercontent.com/29090346/224857392-97d78de7-7ac4-453f-92ad-28c4e8d9923d.png)
brightness option changed (in waterframes)
![2023-03-13_15h33_34](https://user-images.githubusercontent.com/29090346/224857487-99d7292c-f202-47ff-bedf-ecde138dfc1c.png)

***

### MAKEUP ULTRAFAST 8.7a
<video src="https://user-images.githubusercontent.com/29090346/224857030-71fe7a44-859a-4e27-b933-0996ad45b866.mp4"></video>

***

### ASTRAL ALEX
Low settings (disabled realistic clouds)
![2023-03-13_17h42_27](https://user-images.githubusercontent.com/29090346/224857778-6417b995-c03a-469a-a5d8-fb72c8dc530b.png)

Low settings (enabled realistic clouds)
![2023-03-13_17h58_46](https://user-images.githubusercontent.com/29090346/224857927-322698e8-49d1-4aab-a3ca-e559b9b160f3.png)

**Comment by SrRapero720** [comment]
Oculus console output BSL
https://gist.github.com/SrRapero720/dc2863f1ed1c11fb4d668bd442bc4a85

**Comment by SrRapero720** [comment]
BSL owner answer
![image](https://user-images.githubusercontent.com/29090346/225005165-43c20fc9-97de-4118-ae1f-204f5506dee4.png)

**Comment by javiergcim** [comment]
You are not using the correct version of MakeUp for the version of Iris you are using.

The latest version of MakeUp makes use of custom Uniforms. But the version of Iris you use doesn't understand them, you should use a version of Iris that supports them (the latest one). The problem is revealed by that orange sky in the video.

Volumetric clouds in MakeUp are painted in the deferred shader (a step that takes place between drawing opaque objects and translucent objects). This with the purpose that the clouds can be seen "behind" the translucent objects, which will be painted later...

... but I don't think that's the problem, because the deferred shader is used the same with or without volumetric clouds. What IS USED DIFFERENTLY when realistic clouds are enabled is the vanilla cloud shader (gbuffers_clouds), which directly paints a black color with no opacity (so you don't see anything) when realistic clouds are enabled.

If what your painting depends on that step, nothing will be seen.

**Comment by javiergcim** [comment]
It is my understanding that the Optifine/Iris drawing steps will have some correspondence to the lower level native Minecraft steps.

I think you should prevent your drawing from depending on the native step that makes the vanilla clouds draw.

**Comment by SrRapero720** [comment]
@javiergcim Gracias, tengo una noción más o menos de por donde buscar
Aunque sigo un poco perdido de como arreglarlo, ya que el codigo no hace referencia en nada a ese paso y la mayoria de los "intentos de arreglarlo" no me parecen dar resultados (tendre que consultar con algunas personas)

De igual forma gracias.
