### ISSUE TITLE
Works with Sound Physic Remastered mod

### ISSUE THREAD

**Issue by VirtualGaming1** [SrRapero720/WATERFrAMES#109]
I am starting to use this and I use a mod the effects with sound. I am using the curseforge mod that is being work on by Henkelmax and the mod will soften or completely block sound though blocks it also make reverbs on some blocks like stone like in a cave.

Link to the mod page: https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered

**Comment by SrRapero720** [comment]
see #73 and #50

**Comment by SrRapero720** [comment]
the Sound Physics remastered thing was requested before, the issue was pinned since its creation
pay attention next time

**Comment by VirtualGaming1** [comment]
> the Sound Physics remastered thing was requested before, the issue was pinned since its creation pay attention next time

I did a searched on the issue search and it did not pop up in it. also the last part is a bit rude

**Comment by SrRapero720** [comment]
intention wasn't begin rude, english is not my main language and some "cultural" wording isn't good.
despite that, you didn't searched properly because the issue title of (50) is (and quoting) "Feature Request: Sound Physics Remastered compat", and not only that is at the top of the issues tab. So... look closer next time(?
