### ISSUE TITLE
Suggestion: option in the displays to mute Minecraft BGM while in it's sound range

### ISSUE THREAD

**Issue by diefesson** [SrRapero720/WATERFrAMES#112]
Problem: sometimes both the display and Minecraft BGM plays at same time resulting in the display sound being hard to understand.

Current: currently the solution requires ever player in range manually muting they BGM. Harming user experience

Improvement: option in the displays to mute Minecraft BGM while in it's sound range

**Comment by SrRapero720** [comment]
i will look into it

**Comment by SrRapero720** [comment]
Here is the patch
[disable_minecraft_background_music_when_WF_displays_is_nearby.patch](https://github.com/user-attachments/files/16940023/disable_minecraft_background_music_when_WF_displays_is_nearby.patch)

i decided to not integrate this yet because i don't feel confortable. Honestly end-user must mute BG music.

sorry but i will not integrate this
