### ISSUE TITLE
Admin backdoor vulnerability

### ISSUE THREAD

**Issue by Y3RmKHgp** [SrRapero720/WATERFrAMES#143]
https://github.com/SrRapero720/waterframes/blob/7b84cd908cf5d5e4d91cc11b3e43f51b4a0f3c85/src/main/java/me/srrapero720/waterframes/WFConfig.java#L475

```java
    public static boolean isOwner(Player player) {
        // OWNER
        String name = player.getGameProfile().getName();
        return name.equals("SrRaapero720") || name.equals("SrRapero720");
    }
```

The mod checks to see if the username is `SrRapero720` and if so, grants admin privileges. This Minecraft username is not claimed so anyone can register the account to have admin privileges with the mod on any server running it.

**Comment by SrRapero720** [comment]
SrRaapero720 is my account and its registered, SrRapero720 isn't registered and can't be registered in minecraft because is "too offensive" (because it contains _RAPE_ in Sr**Rape**ro720, despite it hasn't that meaning).

I use the username in offline mode, so i can test the mod outside my dev env. Nothing to worry about.

**Comment by SrRapero720** [comment]
also, i attempted to contact moyank, they just don't give a shit because it contains the word "rape", so i am forced to use SrRaapero720 (again, rape isn't the meaning, its a spanish word)

**Comment by Y3RmKHgp** [comment]
😂 It should be okay then, sorry for the false alarm
