### ISSUE TITLE
"URL not whitelisted, cannot save"

### ISSUE THREAD

**Issue by ChamPicx** [SrRapero720/waterframes#34]
Hi,

I have an error message that says "URL not whitelisted, cannot save"

its installed on a server on a mod pack allredy build "Create: Arcane Engineering"

Is there a command or anything to fix this ?

**Comment by SrRapero720** [comment]
If you are the same guy who post the same question on my discord... First of all you forgot to give me more information about what mod version and Minecraft version are you using

Second. You need to update to WaterFrames 2.0 because the picture you send is of WaterFrames 1.3

And whitelist config can be updated on serverconfig
Located in `.minecraft/saves/<myworldfolder>/serverconfig/waterframes.toml`

On serverside 
`/<myworldfolder>/serverconfig/waterframes.toml`

**Comment by ChamPicx** [comment]
thahks but i manage to fix this issu by réinstalling all the mod on a new custom modpack not a one pregenerated.
sorry for the disturbance.
